### ISSUE TITLE
Can't create tasks

### ISSUE THREAD

**Issue by ghost** [BurningOKR/BurningOKR#135]
**Describe the bug**
I can't create tasks for Key Results. There is no button for creating tasks.
I have Admin permissions.

**To Reproduce**
1. Go to 'Tasks' panel.
->No button for creating tasks visible. Neither in columns nor in swimlanes view.

**Expected behavior**
There is a butto to create tasks.

**Screenshots**
<img width="959" alt="Screenshot" src="https://user-images.githubusercontent.com/99714573/154209352-adbe9e06-dc42-4469-a80c-25147be332a1.png">

**Desktop (please complete the following information):**
 - OS: Win 10 Profressional
 - Browser: Firefox 92.0 (and others)
 - Version: 1.4.1 (10.01.2022)

**Comment by MeepMr** [comment]
There is not button to add Tasks to the Taskboard, because the WebSocket connection between your browser and the backend is not working properly.
When you reload the page and then click on the task-tab, is there an error-message coming up at the top of the screen saying that there is no websocket connection?

**Comment by lindihop** [comment]
Yes, that's right. Here is the error message I get:
![grafik](https://user-images.githubusercontent.com/99714573/154923083-a7c0b280-db07-4ae0-86fa-406dcea79892.png)

When I use Edge it's the same so it doesn't seem to be abrowser specific issue. What can we do about this?

**Comment by MeepMr** [comment]
How is the Application deployed?
Is it running on your local machine or is it hosted on a server?
If it is hosted on a server, there might be some firewall, ips,  etc. blocking the requests.

**Comment by lindihop** [comment]
The application is running on a server. I'll have our technichal support check out the issue and get back with the results. Thanks so far!

**Comment by ssc-eves** [comment]
Hey there, i'm the mentioned technical support :)

We deployed it on a Ubuntu 18.04 Server via docker. Even when accessing it from the same subnet without any firewall in between we see the WebSocket error.

Log from the Chrome development tools console: "VM15:1 WebSocket connection to 'ws://172.16.9.124:8080/wsregistry' failed:" <-- we expose port 8080 instead of 4200 as in your docker-compose.yml
Log from nginx: "burning-okr-frontend | 172.16.9.111 - - [22/Feb/2022:12:57:26 +0000] "GET /wsregistry HTTP/1.1" 200 2144 "-" "Mozilla..."

I'm not that pro regarding WebSocket, but shouln't "/wsregistry" be a part of the nginx.conf?

**Comment by MeepMr** [comment]
Yes, there is someting not working as inteded. I reproduced the bug on my end and am trying some fix-ideas

**Comment by rosquillas** [comment]
This URL `https://github.com/burningokr/burningokr/releases/latest`
Leads to version 1.4.3 instead of 1.4.5. I think this is part of the issue

**Comment by EcCo18** [comment]
Hi, we updated our latest path to the newest pre-release. In the next days we will make a new release to fix the problems that are occuring with the websocket connection.

**Comment by MeepMr** [comment]
The beforementioned pre-release is now available here https://github.com/BurningOKR/BurningOKR/releases/tag/1.4.7 hope this fixes the issue now.

**Comment by ssc-eves** [comment]
Hi,

it's still throwing the same error in 1.5.0
