### ISSUE TITLE
Make dashboard and UI friendly

### ISSUE THREAD

**Issue by Gum97** [BurningOKR/BurningOKR#145]
Thank you for your input, but is it possible to make the interface more modern and user-friendly

![image](https://user-images.githubusercontent.com/21122797/156128709-1f43c008-3d5d-4c6f-99e9-d896c766019c.png)
![image](https://user-images.githubusercontent.com/21122797/156128888-6bdb71e3-0a8b-4c3c-bc07-02ae1dc062df.png)

**Comment by MrMutantus** [comment]
Hello Gum97,
thank you for your input.
Since BruningOKR is open source, feel free to redesign the frontend for your own purpose.

We discussed your idea in our team, and will take a further look in future. At the moment we have some topics with a higher priority.

Are there some specific topics, where we can make our frontend more user-friendly?
