### ISSUE TITLE
Websocket Connection in Tasks tab not working v1.5.0

### ISSUE THREAD

**Issue by ssc-eves** [BurningOKR/BurningOKR#223]
**Describe the bug**
We encounter the same issue as for the last versions. You go to the tasks tab and get the error message: "Websocket connection could not be established. Changes are currently not adopted." Sometimes the + button is shown and if you click on it the error appears.

**To Reproduce**
1. Setup BurningOKR with docker-compose
2. Go to Tasks

**Expected behavior**
The site should work

**Screenshots**
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/100208669/222070335-dc4935ff-a1bc-4a7b-9014-0baa498b4339.png">

**Desktop (please complete the following information):**
 - OS: MacOS/Windows
 - Browser: Chrome, Safari, Firefox
 - Version: 1.5.0

**Additional context**
Same as #157 and #135 

By the way: The BurningOKR menu tells it is on v1.0.0:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/100208669/222072276-196317f2-2190-4ae2-acb4-f405db8d7391.png">
Clicking on it reveals an old changelog:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/100208669/222072443-135d9078-99b8-4683-848a-6f55a085407c.png">
So maybe an issue with the docke(-compose) config?

**Comment by MeepMr** [comment]
Hey, thanks for reaching out to us. As I can see in your last screenshot, you are running version 1.4.1, The issue with the websocket-connection is known and should be fixed in version 1.4.7.
Since you mention it not Working in Version 1.5.0 could you please try Version 1.4.7 or 1.4.8? We found a lot of issues on Version 1.5.0 and are currently working on them.

As another hint: We now build dokcer-images and publish them on github, so there shouldn't be the need to build them yourself, unless you made some code-changes yourself.
docker pull ghcr.io/burningokr/b-okr-backend:1.4.8
docker pull ghcr.io/burningokr/b-okr-frontend:1.4.8

With the following docker-compose.yaml it should be easy to make my requested changes.
You still need to use your backend.env and postgres.env Files, simmilar to the old docker-compose.
https://raw.githubusercontent.com/BurningOKR/BurningOKR/master/docker/docker-compose-prod.yml

In case this does not fix the issue, could you please tell me, which Authentication-Method you are using?

**Comment by MeepMr** [comment]
The issue with the wrong version-number showing inside the burger-menu is because it displays the version-number from the package.json. When using the old method of out dokcer-deployment it always is 1.0.0, When we build the images or our release-artifacts we inject the correct Version into the package.json using GitHub Actions. So it is known to us, but it will remain this way for the forseable future. (Another reason, why we decided to publish our own docker-images)

**Comment by EcCo18** [comment]
Hi, I also added doc for using the docker compose prod file to the readme (see Quick start section at the beginning). It's currently only on the [development branch](https://github.com/BurningOKR/BurningOKR/tree/development) but will be merged on master soon.

**Comment by ssc-eves** [comment]
Hi, thanks for the explanations. Used 1.5.0 from the repo now. Small hint: docker-compose logs still says Version 1.0.0 under the logo:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/100208669/222089755-d4f92e13-6834-4c0d-86c2-e428463cd3f2.png">

Adding Tasks is working now, i had to use a different reverse proxy though but it's fine.

**Comment by EcCo18** [comment]
Thanks for the hint. Glad we could help. Why did you have to use a different reverse proxy?

**Comment by ssc-eves** [comment]
We used the Web Application Proxy from Microsoft. The log was throwing an error:
`burning-okr-backend | [2023-03-01 09:00:18.972] [ERROR] [org.springframework.web.socket.messaging.StompSubProtocolHandler] - Error publishing SessionDisconnectEvent[sessionId=f, CloseStatus[code=1006, reason=null]]
burning-okr-backend | java.lang.RuntimeException: StompHeaderAccessor does not contain (valid) userId.`

I don't know if the HTTP Headers are meant, but we had similar issues that the Microsoft WAP has issues with some Headers, so i switched to the Zevenet Loadbalancer/Reverse Proxy which works. I guess NGINX etc. should work aswell.

**Comment by EcCo18** [comment]
Ok, thank you for the explanation. I will close this issue now.
